version: '3.1'

services:
  frontend:
    build:
      context: frontend

  backend:
    build:
      context: backend
    secrets:
      - db-password
    depends_on:
      db:
        condition: service_healthy
  
  db:
    build: db/
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password

secrets:
  db-password:
    file: db/password.txt