services:
  db:
    ports:
      - 33061:3306

  backend:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/src/
      - obj:/src/obj
    ports:
      - 5134:5134
  
  frontend:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - 80:4200
    volumes:
      - ./frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules

volumes:
  node_modules:
  obj:
