services:
  db:
    ports:
      - 33061:3306

  backend:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/src/
      - /src/Application/obj
      - /src/Application/bin
      - /src/Domain/obj
      - /src/Domain/bin
      - /src/Infrastructure/obj
      - /src/Infrastructure/bin
      - /src/Web/obj
      - /src/Web/bin
    ports:
      - 5134:5134
  
  frontend:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - 80:4200
    volumes:
      - ./frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules

volumes:
  node_modules:
